#!/usr/bin/env bash
# Moving an url permanently
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Hello World" > /var/www/html/index.html
sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=EgBJmlPo8Xw permanent;\n}\n' /etc/nginx/sites-available/default 
service nginx start
