#!/usr/bin/env bash
# Moving an url permanently
sudo apt-get -y update
sudo apt-get -y install nginx
echo -e "Hello World" > /var/www/html/index.html
sudo chmod 777 /etc/nginx/sites-available/
sudo chmod 777 /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=EgBJmlPo8Xw permanent;' /etc/nginx/sites-available/default 
sudo service nginx start
