#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, 
# but in the 9th iteration displays "Hi"

i=0

while [ $i -lt 10 ]
do
  echo "Best School"
  if [ $i -eq 8 ]
  then
    echo "Hi"
  fi
  ((i++))
done
