#!/usr/bin/env bash
# This script is iterating 20th times displaying the numbers, 
# but in the 4th iteration displays "bad luck from China",
# the 9th iteration displays "bad luck from Japan"
# and the 17th iteration displays "bad luck from Italy"

i=1

while [ $i -le 20 ]
do
  echo "$i"
  case $i in
  4)
    echo "bad luck from China"
    ;;  
  9)
    echo "bad luck from Japan"
    ;;
  17)
    echo "bad luck from Italy"
    ;;
  esac
  ((i++))
done
